Update styles for Notes page
upleveled/next-js-example-fall-2023-atvie pull request #26
Opened 2024-01-25 15:04 UTC by ProchaLu

Update styling for the Notes page.

2024-01-25 17:51 UTC, karlhorky commented on app/notes/CreateNotesForm.tsx
> -
let's not remove these empty lines, if Prettier lets us

2024-01-25 17:51 UTC, karlhorky commented on app/notes/CreateNotesForm.tsx
> -
let's not remove these empty lines, if Prettier lets us

2024-01-25 17:52 UTC, karlhorky commented on app/notes/page.tsx
> +                  <Link key={`notes-div-${note.id}`} href={`/notes/${note.id}`}>
probably invalid HTML here

2024-01-25 17:55 UTC, karlhorky commented on app/notes/page.tsx
> +      <div className={styles.notePage}>
empty line here

cc @Eprince-hub

2024-01-25 17:55 UTC, karlhorky commented on app/notes/page.tsx
> +        <CreateNoteForm />
empty line here

cc @Eprince-hub

2024-01-26 08:54 UTC, ProchaLu commented on app/notes/CreateNotesForm.tsx
> -
Added the line breaks again 
[0c9718a](https://github.com/upleveled/next-js-example-fall-2023-atvie/pull/26/commits/0c9718ab93cfae955a0453f7e465a27e919b39b5)

2024-01-26 08:54 UTC, ProchaLu commented on app/notes/CreateNotesForm.tsx
> -
Added the line breaks again
[0c9718a](https://github.com/upleveled/next-js-example-fall-2023-atvie/pull/26/commits/0c9718ab93cfae955a0453f7e465a27e919b39b5)

2024-01-26 08:55 UTC, ProchaLu commented on app/notes/page.tsx
> +                  <Link key={`notes-div-${note.id}`} href={`/notes/${note.id}`}>
Changed it to valid HTML. Only `li` elements are allowed as direct children of an `ul` element.
[0c9718a](https://github.com/upleveled/next-js-example-fall-2023-atvie/pull/26/commits/0c9718ab93cfae955a0453f7e465a27e919b39b5)

2024-01-26 08:55 UTC, ProchaLu commented on app/notes/page.tsx
> +      <div className={styles.notePage}>
Added a line break
[0c9718a](https://github.com/upleveled/next-js-example-fall-2023-atvie/pull/26/commits/0c9718ab93cfae955a0453f7e465a27e919b39b5)

2024-01-26 08:55 UTC, ProchaLu commented on app/notes/page.tsx
> +        <CreateNoteForm />
Added an empty line 
[0c9718a](https://github.com/upleveled/next-js-example-fall-2023-atvie/pull/26/commits/0c9718ab93cfae955a0453f7e465a27e919b39b5)

2024-01-26 10:57 UTC, ProchaLu commented on app/animals/dashboard/AnimalsForm.module.scss
> -    }
Styling removed as it is reused on the notes page, and cetralised in `globals.scss`

2024-01-26 11:07 UTC, Eprince-hub commented on app/notes/CreateNotesForm.tsx
> +      <div>
Why do we need this `div` wrapper when the `h2` and the `form` can sit directly inside the first `div`?

2024-01-26 11:12 UTC, ProchaLu commented on app/notes/CreateNotesForm.tsx
> +      <div>
`noteForm` is the grid component, without the child `div` I can't use `position: sticky`.

2024-01-26 11:17 UTC, ProchaLu commented on app/globals.scss
> +}
Added centralized `label` and `input` styles

2024-01-26 11:17 UTC, ProchaLu commented on app/notes/CreateNotesForm.tsx
> -  }
Inlined function

2024-01-26 11:20 UTC, ProchaLu commented on app/notes/notes.module.scss
> +    }
Have to add this `div`,  because it allows the use of `position: sticky`.
https://github.com/upleveled/next-js-example-fall-2023-atvie/pull/26/files#r1467524719

2024-01-26 11:20 UTC, ProchaLu commented on app/notes/notes.module.scss
> +    list-style: none;
Removed the dots for the `list-style`

2024-01-26 11:26 UTC, Eprince-hub commented on app/notes/CreateNotesForm.tsx
> +      <div>
Okay, just saw the comment also on the code

2024-01-26 11:30 UTC, Eprince-hub commented on app/notes/CreateNotesForm.tsx
Maybe we should also do this in this PR CC @karlhorky 
In the animal dashboard we used `AnimalsForm` as the name for the client component, maybe we should also use `NotesForm` on this one instead of `CreateNotesForm` to be uniform?

2024-01-26 11:31 UTC, karlhorky approved these changes

2024-01-26 11:31 UTC, karlhorky commented on app/notes/CreateNotesForm.tsx
sure cc @ProchaLu

2024-01-26 11:31 UTC, karlhorky requested changes
blocking on Victor's comment

2024-01-26 11:34 UTC, ProchaLu commented on app/notes/CreateNotesForm.tsx
nice idea, will update

2024-01-26 11:35 UTC, karlhorky commented on app/notes/CreateNotesForm.tsx
> +import styles from './notes.module.scss';
naming of this file also needs to be fixed

2024-01-26 11:36 UTC, ProchaLu commented on app/notes/CreateNotesForm.tsx
> +import styles from './notes.module.scss';
Saw it, will update to `Notes...`

2024-01-26 11:37 UTC, karlhorky commented on app/notes/CreateNotesForm.tsx
oh, looks like the scss file is also named incorrectly (filename before `.module.scss` needs to match):

![Screenshot 2024-01-26 at 12 36 02](https://github.com/upleveled/next-js-example-fall-2023-atvie/assets/1935696/5d43eb90-be2f-4642-91b9-bd917b2bf796)

added a comment:

- https://github.com/upleveled/next-js-example-fall-2023-atvie/pull/26/files?w=1#r1467554403

2024-01-26 11:38 UTC, Eprince-hub commented on app/globals.scss
Let's remove this background from the error message, it doesn't look good

https://github.com/upleveled/next-js-example-fall-2023-atvie/blob/8b460560ed63d9d4787fe095b748e061380497e6/app/globals.scss#L42

![Screenshot 2024-01-26 at 12 38 45](https://github.com/upleveled/next-js-example-fall-2023-atvie/assets/74430629/a4cf98b5-e22f-4209-97b5-63eb780591c9)

2024-01-26 11:53 UTC, ProchaLu commented on app/globals.scss
Removed in this commit 
[9405c98](https://github.com/upleveled/next-js-example-fall-2023-atvie/pull/26/commits/9405c98068dc0b988e5c2345f70a7b5d7b35ff18)

2024-01-26 11:54 UTC, ProchaLu commented on app/notes/CreateNotesForm.tsx
Updated the filenames in this commit
[4cdc9f4](https://github.com/upleveled/next-js-example-fall-2023-atvie/pull/26/commits/4cdc9f46e4bc009e6f4febb3fccc109884000bdf)

2024-01-26 12:25 UTC, ProchaLu commented on app/notes/page.tsx
> -  );
moved to `NoteForm` component

2024-01-26 12:27 UTC, ProchaLu commented on app/notes/CreateNotesForm.tsx
> +import styles from './notes.module.scss';
Updated filenames in this commit

[9405c98](https://github.com/upleveled/next-js-example-fall-2023-atvie/pull/26/commits/9405c98068dc0b988e5c2345f70a7b5d7b35ff18)

2024-01-26 12:33 UTC, karlhorky commented on app/notes/page.tsx
> +import NoteForm from './NotesForm';
variable name

2024-01-26 12:40 UTC, ProchaLu commented on app/animals/dashboard/AnimalsForm.tsx
> -                      className={styles.button}
Removed, since we don't have this styling anymore

2024-01-26 12:40 UTC, ProchaLu commented on app/animals/dashboard/AnimalsForm.tsx
> -              <button className={styles.button}>
Removed, since we don't have this styling anymore

2024-01-26 12:43 UTC, karlhorky approved these changes

2024-01-26 12:44 UTC, merged